<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 car-1.glb --transform
Author: wallon (https://sketchfab.com/realwallon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-car-09431a8df4344a84aa83a4095bef10fc
Title: Cartoon Car
-->

<script lang="ts">
	import { T } from '@threlte/core';
	import { useDraco, useGltf } from '@threlte/extras';
	import { AutoColliders } from '@threlte/rapier';
	import type { RenderProps } from '../../../types/render-props';

	let { fallback, error, children, ref = $bindable(), ...props } = $props<RenderProps>();

	const dracoLoader = useDraco();

	const gltf = useGltf('/models/world-assets/lambo-car-transformed.glb', { dracoLoader });
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<AutoColliders shape="convexHull">
			<T.Group scale={0.02} position={[0, 0, -10]} rotation={[0, 6, 0]}>
				<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={[0.5, 0.54, 0.55]}>
					<T.Mesh
						geometry={gltf.nodes.Lamborghini_Aventador_Body__Lamborghini_AventadorLam_0.geometry}
						material={gltf.materials.Lamborghini_AventadorLam}
					/>
					<T.Mesh
						geometry={gltf.nodes.Lamborghini_Aventador_Glass__Lamborghini_AventadorLam001_0
							.geometry}
						material={gltf.materials['Lamborghini_AventadorLam.001']}
					/>
					<T.Mesh
						geometry={gltf.nodes.Lamborghini_Aventador_Wheel_FL__Lamborghini_AventadorLam_0
							.geometry}
						material={gltf.materials.Lamborghini_AventadorLam}
					/>
					<T.Mesh
						geometry={gltf.nodes.Lamborghini_Aventador_Wheel_FR__Lamborghini_AventadorLam_0
							.geometry}
						material={gltf.materials.Lamborghini_AventadorLam}
					/>
					<T.Mesh
						geometry={gltf.nodes.Lamborghini_Aventador_Wheel_RL__Lamborghini_AventadorLam_0
							.geometry}
						material={gltf.materials.Lamborghini_AventadorLam}
					/>
					<T.Mesh
						geometry={gltf.nodes.Lamborghini_Aventador_Wheel_RR__Lamborghini_AventadorLam_0
							.geometry}
						material={gltf.materials.Lamborghini_AventadorLam}
					/>
				</T.Group>
			</T.Group>
		</AutoColliders>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
