<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 carpet.glb --transform
Author: mfb64 (https://sketchfab.com/mfb64)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-persian-tudeshk-carpet-ad1d6dc2f6dd4fb5982f64b0b48e4cdf
Title: Old Persian Tudeshk Carpet
-->

<script>
	import { T } from '@threlte/core';
	import { useDraco, useGltf } from '@threlte/extras';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const dracoLoader = useDraco();
	const gltf = useGltf('/models/world-assets/carpet-transformed.glb', { dracoLoader });
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group scale={0.01} position={[2, 0, -13]} rotation={[0, Math.PI / 3, 0]}>
			<T.Group position={[0, 663.67, 0]} rotation={[-0.41, -0.42, 0.76]} scale={100}>
				<T.Mesh geometry={gltf.nodes.Plane001_Carpet_0.geometry} material={gltf.materials.Carpet} />
				<T.Mesh
					geometry={gltf.nodes.Plane001_Carpet_0_1.geometry}
					material={gltf.materials.Carpet}
				/>
				<T.Mesh
					geometry={gltf.nodes.Plane001_Carpet_0_2.geometry}
					material={gltf.materials.Carpet}
				/>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
