<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 belly_dance.glb --transform
Author: zhuoyi0904 (https://sketchfab.com/zhuoyi0904)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/belly-dance-3a3ff40c0fa04554954d89a8febbaa9d
Title: Belly Dance
-->

<script lang="ts">
	import { Group } from 'three';

	import { T } from '@threlte/core';
	import { useDraco, useGltf, useGltfAnimations } from '@threlte/extras';
	import { OutlineEffect } from 'three/examples/jsm/Addons.js';
	import type { RenderProps } from './render-props';

	let { fallback, error, children, ref = $bindable(), ...props } = $props<RenderProps>();

	ref = new Group();

	const dracoLoader = useDraco();
	const gltf = useGltf('/models/world-assets/girl-dancing-1-transformed.glb', { dracoLoader });
	export const { actions, mixer } = useGltfAnimations(gltf, ref);

	$effect(() => {
		// unwrap the store
		const acts = $actions;
		if (!acts || !Object.keys(acts).length) return;

		const action = acts['mixamo.com'];
		action.reset().play();

		return () => action.stop();
	});
</script>

<T is={ref} dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group
			name="Sketchfab_Scene"
			scale={1.5}
			position={[2, 0, -7]}
			rotation={[0, -Math.PI / 4, 0]}
		>
			<T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.91}>
				<T.Group name="Belly_Dancefbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<T.Group name="Object_2">
						<T.Group name="RootNode">
							<T.Group name="Object_4">
								<T is={gltf.nodes._rootJoint} />
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_6"
									geometry={gltf.nodes.Object_6.geometry}
									material={gltf.materials.hair_map}
									skeleton={gltf.nodes.Object_6.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_7"
									geometry={gltf.nodes.Object_7.geometry}
									material={gltf.materials.hair_map}
									skeleton={gltf.nodes.Object_7.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_8"
									geometry={gltf.nodes.Object_8.geometry}
									material={gltf.materials.hair_map}
									skeleton={gltf.nodes.Object_8.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_9"
									geometry={gltf.nodes.Object_9.geometry}
									material={gltf.materials.hair_map}
									skeleton={gltf.nodes.Object_9.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_11"
									geometry={gltf.nodes.Object_11.geometry}
									material={gltf.materials.clothing_map}
									skeleton={gltf.nodes.Object_11.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_12"
									geometry={gltf.nodes.Object_12.geometry}
									material={gltf.materials.Eyebrow_map}
									skeleton={gltf.nodes.Object_12.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_13"
									geometry={gltf.nodes.Object_13.geometry}
									material={gltf.materials.Eyebrow_map}
									skeleton={gltf.nodes.Object_13.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_14"
									geometry={gltf.nodes.Object_14.geometry}
									material={gltf.materials.Eyelashes_map}
									skeleton={gltf.nodes.Object_14.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_15"
									geometry={gltf.nodes.Object_15.geometry}
									material={gltf.materials.Eye_map}
									skeleton={gltf.nodes.Object_15.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_16"
									geometry={gltf.nodes.Object_16.geometry}
									material={gltf.materials.Eye_map}
									skeleton={gltf.nodes.Object_16.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_18"
									geometry={gltf.nodes.Object_18.geometry}
									material={gltf.materials.Teeth_map}
									skeleton={gltf.nodes.Object_18.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_19"
									geometry={gltf.nodes.Object_19.geometry}
									material={gltf.materials.Eyelashes_map}
									skeleton={gltf.nodes.Object_19.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_20"
									geometry={gltf.nodes.Object_20.geometry}
									material={gltf.materials.Head_map}
									skeleton={gltf.nodes.Object_20.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_22"
									geometry={gltf.nodes.Object_22.geometry}
									material={gltf.materials.clothing_map}
									skeleton={gltf.nodes.Object_22.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_24"
									geometry={gltf.nodes.Object_24.geometry}
									material={gltf.materials.clothing_map}
									skeleton={gltf.nodes.Object_24.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_26"
									geometry={gltf.nodes.Object_26.geometry}
									material={gltf.materials.Arm_map}
									skeleton={gltf.nodes.Object_26.skeleton}
								/>
							</T.Group>
						</T.Group>
					</T.Group>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T>
