<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 carpet.glb --transform
Author: AMMediaGames (https://sketchfab.com/AMMediaGames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/carpet-ruined-old-free-050a7a44bc344e65a1d63d4902a64e21
Title: Carpet Ruined Old Free
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/carpet-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group scale={0.01}>
      <T.Group
        position={[0, 663.67, 0]}
        rotation={[-0.41, -0.42, 0.76]}
        scale={100}
      >
        <T.Mesh
          geometry={gltf.nodes.Plane001_Carpet_0.geometry}
          material={gltf.materials.Carpet}
        />
        <T.Mesh
          geometry={gltf.nodes.Plane001_Carpet_0_1.geometry}
          material={gltf.materials.Carpet}
        />
        <T.Mesh
          geometry={gltf.nodes.Plane001_Carpet_0_2.geometry}
          material={gltf.materials.Carpet}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
