<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ottoman_pillow_and_carpets_v2.glb --transform
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/ottoman_pillow_and_carpets_v2-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group scale={0.01}>
      <T.Group
        position={[-381.82, 13, 0.43]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <T.Group position={[1.82, 0.43, 0]}>
          <T.Group position={[0, 0, -2.92]}>
            <T.Mesh
              geometry={gltf.nodes.Coussin_frange_Coussin1_0.geometry}
              material={gltf.materials.Coussin1}
              position={[80, 0, -10.08]}
            />
          </T.Group>
          <T.Mesh
            geometry={gltf.nodes.Coussin_Coussin1_0.geometry}
            material={gltf.materials.Coussin1}
            position={[80, 0, -13]}
          />
        </T.Group>
        <T.Group position={[0, 0, -10.8]}>
          <T.Mesh
            geometry={gltf.nodes.Tapis_Tapis1_0.geometry}
            material={gltf.materials.Tapis1}
            position={[81.82, 0.43, -2.2]}
          />
        </T.Group>
      </T.Group>
      <T.Group
        position={[-269.68, 13, 270.29]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
      >
        <T.Group position={[1.82, 0.43, 0]}>
          <T.Group position={[0, 0, -2.92]}>
            <T.Mesh
              geometry={gltf.nodes.Coussin_frange001_Coussin4_0.geometry}
              material={gltf.materials.Coussin4}
              position={[80, 0, -10.08]}
            />
          </T.Group>
          <T.Mesh
            geometry={gltf.nodes.Coussin001_Coussin4_0.geometry}
            material={gltf.materials.Coussin4}
            position={[80, 0, -13]}
          />
        </T.Group>
        <T.Group
          position={[26.3, -19.19, -10.8]}
          rotation={[0, 0, 0.09]}
        >
          <T.Mesh
            geometry={gltf.nodes.Tapis001_Tapis4_0.geometry}
            material={gltf.materials.Tapis4}
            position={[81.81, 0.43, -2.2]}
          />
        </T.Group>
      </T.Group>
      <T.Group
        position={[0.43, 13, 381.82]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      >
        <T.Group position={[1.82, 0.43, 0]}>
          <T.Group position={[0, 0, -2.92]}>
            <T.Mesh
              geometry={gltf.nodes.Coussin_frange002_Coussin3_0.geometry}
              material={gltf.materials.Coussin3}
              position={[80, 0, -10.08]}
            />
          </T.Group>
          <T.Mesh
            geometry={gltf.nodes.Coussin002_Coussin3_0.geometry}
            material={gltf.materials.Coussin3}
            position={[80, 0, -13]}
          />
        </T.Group>
        <T.Group
          position={[0, 0, -10.8]}
          rotation={[0, 0, -1.48]}
        >
          <T.Mesh
            geometry={gltf.nodes.Tapis002_Tapis3_0.geometry}
            material={gltf.materials.Tapis3}
            position={[81.82, 0.43, -2.2]}
          />
        </T.Group>
      </T.Group>
      <T.Group
        position={[270.29, 13, 269.68]}
        rotation={[-Math.PI / 2, 0, 2.36]}
      >
        <T.Group position={[1.81, 0.43, 0]}>
          <T.Group position={[0, 0, -2.92]}>
            <T.Mesh
              geometry={gltf.nodes.Coussin_frange003_Coussin2_0.geometry}
              material={gltf.materials.Coussin2}
              position={[80, 0, -10.08]}
            />
          </T.Group>
          <T.Mesh
            geometry={gltf.nodes.Coussin003_Coussin2_0.geometry}
            material={gltf.materials.Coussin2}
            position={[80, 0, -13]}
          />
        </T.Group>
        <T.Group position={[0, 0, -10.8]}>
          <T.Mesh
            geometry={gltf.nodes.Tapis003_Tapis2_0.geometry}
            material={gltf.materials.Tapis2}
            position={[81.81, 0.43, -2.2]}
          />
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
