<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 car-1.glb --transform
Author: wallon (https://sketchfab.com/realwallon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-car-09431a8df4344a84aa83a4095bef10fc
Title: Cartoon Car
-->

<script lang="ts">
	import { T } from '@threlte/core';
	import { useDraco, useGltf } from '@threlte/extras';
	import { AutoColliders } from '@threlte/rapier';
	import type { RenderProps } from './render-props';

	let { fallback, error, children, ref = $bindable(), ...props } = $props<RenderProps>();

	const dracoLoader = useDraco();

	const gltf = useGltf('/models/world-assets/car-1-transformed.glb', { dracoLoader });
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<AutoColliders shape="trimesh">
			<T.Group scale={0.0035} position={[0, -0.46, -10]} rotation={[0, 6, 0]}>
				<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
					<T.Mesh
						castShadow
						receiveShadow={false}
						frustumCulled={true}
						geometry={gltf.nodes.black_floats_Pure_black_0.geometry}
						material={gltf.materials.Pure_black}
					/>
					<T.Mesh
						castShadow
						receiveShadow={false}
						frustumCulled={true}
						geometry={gltf.nodes.black_floats_chrome_0.geometry}
						material={gltf.materials.chrome}
					/>
				</T.Group>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.body_car_body_0.geometry}
					material={gltf.materials.car_body}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.hood_car_body_0.geometry}
					material={gltf.materials.car_body}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.front_bumper_carbon_fiber_0.geometry}
					material={gltf.materials.carbon_fiber}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.front_fenders_carbon_fiber_0.geometry}
					material={gltf.materials.carbon_fiber}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.Plane006_car_body_0.geometry}
					material={gltf.materials.car_body}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.Plane008_window_0.geometry}
					material={gltf.materials.window}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.Plane009_black_parts_0.geometry}
					material={gltf.materials.black_parts}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.Plane007_black_parts_0.geometry}
					material={gltf.materials.black_parts}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.trunk_car_body_0.geometry}
					material={gltf.materials.car_body}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.black_parts_black_parts_0.geometry}
					material={gltf.materials.black_parts}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.rear_fenders_carbon_fiber_0.geometry}
					material={gltf.materials.carbon_fiber}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.headlight_glass_headlight_glass_0.geometry}
					material={gltf.materials.headlight_glass}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.Plane026_chrome_0.geometry}
					material={gltf.materials.chrome}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.rear_bumper_carbon_fiber_0.geometry}
					material={gltf.materials.carbon_fiber}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.exhaust_chrome_0.geometry}
					material={gltf.materials.chrome}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.Plane005_black_parts_0.geometry}
					material={gltf.materials.black_parts}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.side_skirts_carbon_fiber_0.geometry}
					material={gltf.materials.carbon_fiber}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.Plane011_window_0.geometry}
					material={gltf.materials.window}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.Plane014_black_parts_0.geometry}
					material={gltf.materials.black_parts}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.Plane017_window_0.geometry}
					material={gltf.materials.window}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.Plane033_black_parts_0.geometry}
					material={gltf.materials.black_parts}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.Plane034_black_parts_0.geometry}
					material={gltf.materials.black_parts}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.Plane035_window_0.geometry}
					material={gltf.materials.window}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.Plane036_black_parts_0.geometry}
					material={gltf.materials.black_parts}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.mirrors_chrome_0.geometry}
					material={gltf.materials.chrome}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.front_right_wheel_wheel_0.geometry}
					material={gltf.materials.wheel}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.Plane038_black_parts_0.geometry}
					material={gltf.materials.black_parts}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.intercooler_intercooler_0.geometry}
					material={gltf.materials.intercooler}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.rear_wheels_wheel_0.geometry}
					material={gltf.materials.wheel}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<T.Mesh
					castShadow
					receiveShadow={false}
					frustumCulled={true}
					geometry={gltf.nodes.front_left_wheel_wheel_0.geometry}
					material={gltf.materials.wheel}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
			</T.Group></AutoColliders
		>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
