<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 /Users/varundudeja/Documents/desi-world/static/models/desi-world/CasinoBoard.glb --transform
-->

<script>
	import { Group } from 'three';
	import { T } from '@threlte/core';
	import { useDraco, useGltf } from '@threlte/extras';

	export const ref = new Group();

	const dracoLoader = useDraco();
	const gltf = useGltf('/models/desi-world/CasinoBoard-transformed.glb', { dracoLoader });

	let { ...rest } = $props();
</script>

<T is={ref} dispose={false} {...rest}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Casino_Royal.geometry}
			material={gltf.materials.Concrete}
			position={[-0.02, 3.72, -32.74]}
			scale={0.66}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
