<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 /Users/varundudeja/Documents/desi-world/static/models/desi-world/CasinoDoor.glb --transform
-->

<script>
	import { Group } from 'three';
	import { T } from '@threlte/core';
	import { useDraco, useGltf } from '@threlte/extras';

	export const ref = new Group();

	const dracoLoader = useDraco();
	const gltf = useGltf('/models/desi-world/CasinoDoor-transformed.glb', { dracoLoader });

	let { ...rest } = $props();
</script>

<T is={ref} dispose={false} {...rest}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={[-0.02, 0.03, -22.44]} scale={1.17}>
			<T.Mesh geometry={gltf.nodes.Cube003.geometry} material={gltf.materials.Grey} />
			<T.Mesh geometry={gltf.nodes.Cube003_1.geometry} material={gltf.materials.Brown} />
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
