<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 /Users/varundudeja/Documents/desi-world/static/models/desi-world/EntrySign.glb --transform
-->

<script>
	import { Group } from 'three';
	import { T } from '@threlte/core';
	import { useDraco, useGltf } from '@threlte/extras';
	import { AutoColliders } from '@threlte/rapier';

	export const ref = new Group();

	const dracoLoader = useDraco();
	const gltf = useGltf('/models/desi-world/EntrySign-transformed.glb', { dracoLoader });

	let { ...rest } = $props();
</script>

<T is={ref} dispose={false} {...rest}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<AutoColliders shape={'trimesh'}>
			<T.Mesh geometry={gltf.nodes.Plane004.geometry} material={gltf.materials.Brown} />
			<T.Mesh geometry={gltf.nodes.Plane004_1.geometry} material={gltf.materials.Grey} />
		</AutoColliders>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
