<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 female.glb --transform
-->

<script>
	import { Group } from 'three';

	import { T } from '@threlte/core';
	import { useDraco, useGltf, useGltfAnimations } from '@threlte/extras';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	ref = new Group();

	const dracoLoader = useDraco();

	const gltf = useGltf('/models/female.glb', { dracoLoader });

	export const { actions, mixer } = useGltfAnimations(gltf, ref);
</script>

<T is={ref} dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group name="Root_Scene">
			<T.Group name="RootNode">
				<T is={gltf.nodes.mixamorigHips} />
				<T.SkinnedMesh
					name="Erika_Archer_Eyes_Mesh"
					geometry={gltf.nodes.Erika_Archer_Eyes_Mesh.geometry}
					material={gltf.materials.EyeSpec_MAT}
					skeleton={gltf.nodes.Erika_Archer_Eyes_Mesh.skeleton}
				/>
				<T.SkinnedMesh
					name="Erika_Archer_Body_Mesh"
					geometry={gltf.nodes.Erika_Archer_Body_Mesh.geometry}
					material={gltf.materials.Akai_MAT}
					skeleton={gltf.nodes.Erika_Archer_Body_Mesh.skeleton}
				/>
				<T.SkinnedMesh
					name="Erika_Archer_Clothes_Mesh"
					geometry={gltf.nodes.Erika_Archer_Clothes_Mesh.geometry}
					material={gltf.materials.eyelash_MAT}
					skeleton={gltf.nodes.Erika_Archer_Clothes_Mesh.skeleton}
				/>
				<T.SkinnedMesh
					name="Erika_Archer_Eyelashes_Mesh"
					geometry={gltf.nodes.Erika_Archer_Eyelashes_Mesh.geometry}
					material={gltf.materials.Body_MAT}
					skeleton={gltf.nodes.Erika_Archer_Eyelashes_Mesh.skeleton}
				/>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T>
