<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 girl-dancing-2.glb --transform
Author: lev1953 (https://sketchfab.com/lev1953)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eve-nikke-suit-8ba19ee03f6948278f024cea8765fb7f
Title: EVE Nikke Suit
-->

<script lang="ts">
	import { Group } from 'three';

	import { T } from '@threlte/core';
	import { useDraco, useGltf, useGltfAnimations } from '@threlte/extras';
	import type { RenderProps } from './render-props';

	let { fallback, error, children, ref = $bindable(), ...props } = $props<RenderProps>();

	ref = new Group();
	const dracoLoader = useDraco();

	const gltf = useGltf('/models/world-assets/girl-dancing-2-transformed.glb', { dracoLoader });

	export const { actions, mixer } = useGltfAnimations(gltf, ref);

	$effect(() => {
		// unwrap the store
		const acts = $actions;
		if (!acts || !Object.keys(acts).length) return;

		const action = acts['5363356613632_TempMotion'];
		action.reset().play();

		return () => action.stop();
	});
</script>

<T is={ref} dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group
			name="Sketchfab_Scene"
			scale={1.3}
			position={[-2.4, 0, -8]}
			rotation={[0, Math.PI / 4, 0]}
		>
			<T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
				<T.Group name="EVE_Nikke_Suitfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<T.Group name="Object_2">
						<T.Group name="RootNode">
							<T.Group name="Object_4">
								<T is={gltf.nodes._rootJoint} />
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_7"
									geometry={gltf.nodes.Object_7.geometry}
									material={gltf.materials.Eyes}
									skeleton={gltf.nodes.Object_7.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_9"
									geometry={gltf.nodes.Object_9.geometry}
									material={gltf.materials.Hair_Pin}
									skeleton={gltf.nodes.Object_9.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_11"
									geometry={gltf.nodes.Object_11.geometry}
									material={gltf.materials.EVE_Face}
									skeleton={gltf.nodes.Object_11.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_12"
									geometry={gltf.nodes.Object_12.geometry}
									material={gltf.materials.EVE_Eyelashes}
									skeleton={gltf.nodes.Object_12.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_13"
									geometry={gltf.nodes.Object_13.geometry}
									material={gltf.materials.EVE_EyeBrows}
									skeleton={gltf.nodes.Object_13.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_14"
									geometry={gltf.nodes.Object_14.geometry}
									material={gltf.materials.EVE_Teeth}
									skeleton={gltf.nodes.Object_14.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_16"
									geometry={gltf.nodes.Object_16.geometry}
									material={gltf.materials.Long_Ponytail_Hair}
									skeleton={gltf.nodes.Object_16.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_18"
									geometry={gltf.nodes.Object_18.geometry}
									material={gltf.materials.Nikke_Decal}
									skeleton={gltf.nodes.Object_18.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_19"
									geometry={gltf.nodes.Object_19.geometry}
									material={gltf.materials.Nikke_Suit}
									skeleton={gltf.nodes.Object_19.skeleton}
								/>
								<T.SkinnedMesh
									castShadow
									receiveShadow={false}
									frustumCulled={true}
									name="Object_20"
									geometry={gltf.nodes.Object_20.geometry}
									material={gltf.materials.Nikke_Jacket}
									skeleton={gltf.nodes.Object_20.skeleton}
								/>
							</T.Group>
						</T.Group>
					</T.Group>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T>
