<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 /Users/varundudeja/Documents/My Codes/Antigravity/Desi-world/static/models/world-assets/Plane-2.glb --transform
-->

<script lang="ts">
	import { T } from '@threlte/core';
	import { useDraco, useGltf } from '@threlte/extras';
	import { AutoColliders } from '@threlte/rapier';
	import { isPlane } from '$lib/stores/commonStores';
	import type { RenderProps } from './render-props';
	import { MeshStandardMaterial } from 'three';

	// let props: RenderProps = $props();

	let { fallback, error, children, ref = $bindable(), ...props } = $props<RenderProps>();

	const dracoLoader = useDraco();

	const gltf = useGltf('/models/world-assets/Plane.glb', { dracoLoader });
	gltf.then(() => ($isPlane = true));
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<AutoColliders shape={'trimesh'}>
			<T.Mesh
				geometry={gltf.nodes.Plane.geometry}
				material={new MeshStandardMaterial({
					map: gltf.nodes.Plane.material.map,
					color: 'yellow',
					roughness: 0.8
				})}
				receiveShadow={true}
				castShadow={false}
			/>
		</AutoColliders>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
