<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 /Users/varundudeja/Documents/desi-world/static/models/desi-world/MainGate.glb --transform
-->

<script lang="ts">
	import { T } from '@threlte/core';
	import { useDraco, useGltf } from '@threlte/extras';
	import { AutoColliders } from '@threlte/rapier';
	import type { RenderProps } from './render-props';

	let { fallback, error, children, ref = $bindable(), ...props } = $props<RenderProps>();

	const dracoLoader = useDraco();

	const gltf = useGltf('/models/world-assets/MainGate.glb', { dracoLoader });
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<AutoColliders shape={'trimesh'}>
			<T.Mesh
				position={[0, 0.09, -5]}
				geometry={gltf.nodes.Cube014__0.geometry}
				material={gltf.materials['Scene_-_Root']}
				scale={1.4}
			/>
		</AutoColliders>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
