<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 male.glb --transform
-->

<script>
	import { Group } from 'three';

	import { T } from '@threlte/core';
	import { useDraco, useGltf, useGltfAnimations } from '@threlte/extras';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	ref = new Group();

	const dracoLoader = useDraco();

	const gltf = useGltf('/models/male.glb', { dracoLoader });

	export const { actions, mixer } = useGltfAnimations(gltf, ref);
</script>

<T is={ref} dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group name="Root_Scene">
			<T.Group name="RootNode">
				<T is={gltf.nodes.mixamorigHips} />
				<T.SkinnedMesh
					name="Ch24"
					geometry={gltf.nodes.Ch24.geometry}
					material={gltf.materials.Ch24_Body}
					skeleton={gltf.nodes.Ch24.skeleton}
				/>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T>
