<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 /Users/varundudeja/Documents/desi-world/static/models/desi-world/Plane.glb --transform
-->

<script>
	import { Group } from 'three';
	import { T } from '@threlte/core';
	import { useDraco, useGltf } from '@threlte/extras';
	import { AutoColliders } from '@threlte/rapier';
	import { onMount } from 'svelte';
	import { isPlane } from '$lib/stores/commonStores';

	export const ref = new Group();

	const dracoLoader = useDraco();

	const gltf = useGltf('/models/desi-world/Plane-transformed.glb', { dracoLoader });
	const gltf2 = useGltf('/models/desi-world/Plane-transformed.glb', { dracoLoader }).then((res) => {
		$isPlane = true;
	});

	let { ...rest } = $props();
</script>

<T is={ref} dispose={false} {...rest}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<AutoColliders shape={'trimesh'}>
			<T.Mesh geometry={gltf.nodes.Plane001.geometry} material={gltf.materials.MyGround} />
		</AutoColliders>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
