<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 Starting-Room.glb --transform
-->

<script lang="ts">
	import { T } from '@threlte/core';
	import { useDraco, useGltf } from '@threlte/extras';
	import { AutoColliders } from '@threlte/rapier';
	import type { RenderProps } from './render-props';

	let { fallback, error, children, ref = $bindable(), ...props } = $props<RenderProps>();

	const dracoLoader = useDraco();

	const gltf = useGltf('/models/world-assets/Starting-Room-transformed.glb', { dracoLoader });
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<AutoColliders shape="trimesh">
			<T.Mesh
				geometry={gltf.nodes.Starting_Room.geometry}
				material={gltf.nodes.Starting_Room.material}
			/>
		</AutoColliders>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
